FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --update --no-cache python3 make g++ curl protoc && ln -sf python3 /usr/bin/python

COPY package*.json ./

COPY ./src/protos ./protos

RUN npm install\
&& npm install typescript -g

COPY . .